subinclude("//packaging:tools")

# https://github.com/dgiagio/warp/releases
CONFIG.setdefault("WARP_VERSION", "0.3.0")

warp_binary(
    name = "warp",
    version = CONFIG.WARP_VERSION,
    visibility = ["PUBLIC"],
)
