filegroup(
    name = "kubernetes",
    srcs = [
        "helm.build_defs",
        "kind.build_defs",
    ],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "tools",
    srcs = ["tools.build_defs"],
    visibility = ["PUBLIC"],
)
