subinclude("//openapi:tools")

# https://github.com/stoplightio/spectral/releases
CONFIG.setdefault("SPECTRAL_VERSION", "5.8.1")

spectral_binary(
    name = "spectral",
    version = CONFIG.SPECTRAL_VERSION,
    visibility = ["PUBLIC"],
)
