filegroup(
    name = "go",
    srcs = ["go.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "tools",
    srcs = ["tools.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "combat",
    srcs = ["go.build_defs", "compat.build_defs"],
    visibility = ["PUBLIC"],
)
