name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Please
        uses: sagikazarmark/setup-please-action@v0
        with:
          save-logs: 'true'

      - name: Start KinD cluster
        run: kind create cluster

      - name: Build
        run: plz build //test/...

      - name: Test
        run: plz test --log_file=plz-out/log/test.log //test/...

  build-macos:
    name: Build (MacOS)
    runs-on: macos-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install GNU coreutils
        run: brew install coreutils

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Please
        uses: sagikazarmark/setup-please-action@v0
        with:
          save-logs: 'true'

      - name: Build
        run: plz build --exclude kind --exclude docker //test/...

      - name: Test
        run: plz test --exclude kind --exclude docker --log_file=plz-out/log/test.log //test/...
