name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    env:
      PLZ_ARGS: -p

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start KinD cluster
        run: kind create cluster

      - name: Build
        run: ./pleasew $PLZ_ARGS build //test/...

      - name: Test
        run: ./pleasew $PLZ_ARGS test --log_file=plz-out/log/test.log //test/...

      - name: Save please log output
        uses: actions/upload-artifact@v1
        with:
          name: plz-log
          path: plz-out/log

  build-macos:
    name: Build (MacOS)
    runs-on: macos-latest
    env:
      PLZ_ARGS: -p --exclude kind --exclude docker

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install GNU coreutils
        run: brew install coreutils

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: ./pleasew $PLZ_ARGS build //test/...

      - name: Test
        run: ./pleasew $PLZ_ARGS test --log_file=plz-out/log/test.log //test/...

      - name: Save please log output
        uses: actions/upload-artifact@v1
        with:
          name: plz-log-macos
          path: plz-out/log
