name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      PLZ_ARGS: -p

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start KinD cluster
        run: kind create cluster

      - name: Build
        run: ./pleasew $PLZ_ARGS build //test/...

      - name: Test
        run: ./pleasew $PLZ_ARGS test --log_file=plz-out/log/test.log //test/...

      - name: Save please log output
        uses: actions/upload-artifact@v1
        with:
          name: plz-log
          path: plz-out/log
