name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Please
        uses: sagikazarmark/setup-please-action@v0

      - name: Start KinD cluster
        run: kind create cluster

      - name: Test
        run: plz test //test/...

  test-macos:
    name: Test (MacOS)
    runs-on: macos-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install GNU coreutils
        run: brew install coreutils

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Please
        uses: sagikazarmark/setup-please-action@v0
        with:
          exclude: kind, docker

      - name: Test
        run: plz test //test/...
